country:
  japan: 0
  united_states: 1
  china: 2

industry:
  fis: 0
  mng: 1
  con: 2
  fod: 3
  txt: 4
  pap: 5
  che: 6
  pha: 7
  oil: 8
  rub: 9
  gls: 10
  stl: 11
  nfr: 12
  met: 13
  mac: 14
  elc: 15
  teq: 16
  prc: 17
  mis: 18
  elg: 19
  prl: 20
  shp: 21
  air: 22
  whs: 23
  com: 24
  who: 25
  ret: 26
  bnk: 27
  sec: 28
  ins: 29
  fin: 30
  rea: 31
  svc: 32

market:
  t_1: 0
  t_2: 1
  t_js: 2 
  t_jg: 3
  t_m: 4
  t_f: 5
  s: 6
  s_a: 7 
  m_1: 8
  m_2: 9
  m_c: 10
  f: 11
  f_q: 12

currency:
  usdjpy: 0
  eurjpy: 1

bracket:
  nikkei225: 0
  topix: 1
  jasdaq: 2
  dji: 3
  nasdaq: 4
  sse: 5
  hsi: 6

trend_source:
  nikkei: 0

tag_type:
  category: 0
  trend: 1
  alias: 2
  ignore: 3

commodity:
  gold: 0
  us_wheat: 1
  crude_oil: 2










