country:
  japan: 0
  united_states: 1
  china: 2

industry:
  forestry_fishery: 0
  mining: 1
  building: 2
  food: 3
  fiber: 4
  paper_pulp: 5
  chemical: 6
  medicine: 7
  petroleum_coal: 8
  rubber: 9
  glass_stone: 10
  iron: 11
  metal_exiron: 12
  metal: 13
  machinery: 14
  electrical: 15
  transport_machinery: 16
  precision_machinery: 17
  misc_machinery: 18
  electricity_gas: 19
  land_transport: 20
  shipping: 21
  sky_transport: 22
  warehouse_conveyance: 23
  communication: 24
  wholesale: 25
  retail: 26
  bank: 27
  bill_broker: 28
  insurer: 29
  financial: 30
  estate: 31
  service: 32

market:
  t_1: 0
  t_2: 1
  t_js: 2 
  t_jg: 3
  t_m: 4
  t_f: 5
  s: 6
  s_a: 7 
  m_1: 8
  m_2: 9
  m_c: 10
  f: 11
  f_q: 12

currency:
  usdjpy: 0
  eurjpy: 1

bracket:
  nikkei225: 0
  topix: 1
  jasdaq: 2
  dji: 3
  nasdaq: 4
  sse: 5
  hsi: 6

trend_source:
  nikkei: 0

tag_type:
  category: 0
  trend: 1
  alias: 2
  ignore: 3

commodity:
  gold: 0
  us_wheat: 1
  crude_oil: 2










