development:
  adapter:  mysql2
  encoding: utf8
  database: stock_portal_development
  username: mysql
  password: password
  host:     localhost
  pool:     5
  reconnect: true

test:
  adapter:  mysql2
  encoding: utf8
  database: stock_portal_test
  username: mysql
  password: password
  host:     localhost
  pool:     5

production:
  adapter:   mysql2
  encoding:  utf8
  database:  <%= ENV['RDS_DB_NAME'] %>
  username:  <%= ENV['DB_SSL_USERNAME'] %>
  password:  <%= ENV['DB_SSL_PASSWORD'] %>
  host:      <%= ENV['RDS_HOSTNAME'] %>
  # sslca:     <%= "#{Rails.root}/config/keys/rds-mysql-ssl-ca-cert.pem" %>
  reconnect: true
