development:
  adapter:  mysql2
  encoding: utf8
  database: stock_portal_development
  username: mysql
  password: password
  host:     localhost
  pool:     5
  reconnect: true

test:
  adapter:  mysql2
  encoding: utf8
  database: stock_portal_test
  username: mysql
  password: password
  host:     localhost
  pool:     5
  reconnect: true

staging:
  adapter:  mysql2
  encoding: utf8
  database: stock_portal_staging
  username: mysql
  password: password
  host:     localhost
  pool:     5
  reconnect: true

production:
  adapter:  mysql2
  encoding: utf8
  database: stock_portal
  username: akasatana
  password: yamshim05
  host:     localhost
  # sslca:     <%= "#{Rails.root}/config/keys/rds-mysql-ssl-ca-cert.pem" %>
  reconnect: true
