# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42b1fef95508650ac65b5ad600e5f9a41c46ec8c73d02cdd53c71eca57f40dd9434abd15f81b9327c118f3209cf61330572f84bc0c1cffdd64e221b957836383

test:
  secret_key_base: 95aa6eaf88be5386e591dbf623e1d16c9c52425975aee2774e0fb869cded2075129f2cffe74eeeeca36c42f6e3720dc652846d3d5e21ad7aa2ced1d57108e58b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
